### ISSUE TITLE
Bazel Version

### ISSUE THREAD

**Issue by Manwindersingh03** [google/truestreet#1]
Hi,

Do we need a specific Bazel version and Ubuntu version?

I tried with latest bazel version 3.2.0 and "Ubuntu eoan"and followed the steps mentioned in README.

When I am running-  bazel run //:gazelle, It throws the following error 

ERROR: Skipping '//:gazelle': error loading package '': Unable to find package for @io_bazel_rules_docker//container:container.bzl: The repository '@io_bazel_rules_docker' could not be resolved.

WARNING: Target pattern parsing failed.

ERROR: error loading package '': Unable to find package for @io_bazel_rules_docker//container:container.bzl: The repository '@io_bazel_rules_docker' could not be resolved.

INFO: Elapsed time: 7.468s
INFO: 0 processes.

FAILED: Build did NOT complete successfully (1 packages loaded)

FAILED: Build did NOT complete successfully (1 packages loaded)

    Fetching @rules_cc; Cloning 7e650b11fe6d49f70f2ca7a1c4cb8bcc4a1fe239 of https://github.com/bazelbuild/rules_cc

Can anyone help me here if I am missing out on something here?

**Comment by codeactivist** [comment]
Thank you for reporting the issue, I have just updated the WORKSPACE file. Can you please get the latest copy and try again ?

**Comment by codeactivist** [comment]
Assuming issue is resolved, closing the bug.
