### ISSUE TITLE
Invalid Argument while querying

### ISSUE THREAD

**Issue by sajankgit** [google/truestreet#3]
Hi Team,

I am using truestreet along with cloudspanner for prometheus. 

When I am trying to query `node_load1{instance=~"instance_name"}`, I am getting the following error.
```
500 Internal Server Error: spanner: code = "InvalidArgument", desc = "Syntax error: Unexpected \\\"^\\\" [at 7:57]\\n (name=@name0 AND REGEXP_CONTAINS(value, ^(@value0)$))\\n ^"
```

If I do not use tilde (~) and query just `node_load1{instance="instance_name"}`, I am getting the results fine. 

I was able to use tilde (~) when prometheus was running in a single machine i.e when data was just in the disk

So I cannot query multiple instances in a single query. Can you guys please check this?

**Comment by codeactivist** [comment]
It seems to work fine for us, please check if quotes are somehow messed up during copy/paste.

node_load{instance=~"instance_name1|instance_name2|instance_name3"} should work fine.

As a work around you can try following query to pull node_load for all instances. 
avg(node_load) by (instance)
or 
avg(node_load{job="databases"}) by (instance)

I will build a fresh binary and test more.

**Comment by sajankgit** [comment]
Hi, 

Thanks for checking this.

I am still getting same error. If possible can you also publish binaries also?

**Comment by codeactivist** [comment]
sajankgit@ we are able to reproduce the issue in our setup, spanner query syntax appears to have changed for regular expressions. A fix is being tested and will be pushed to github soon.

**Comment by codeactivist** [comment]
We have pushed the fix to repository, please sync your code and build again.
