### ISSUE TITLE
getting following error while connecting spanner

### ISSUE THREAD

**Issue by anassolanki675** [google/truestreet#5]
2022/04/25 05:47:51 applyMutations error for samples : spanner: code = "NotFound", desc = "Table not found: samples"
2022/04/25 05:48:11 timeSeriesExists error : spanner: code = "InvalidArgument", desc = "Table not found: index [at 1:27]\\nSELECT DISTINCT tsid FROM index WHERE tsid IN UNNEST(@array)\\n                          ^"

**Comment by codeactivist** [comment]
Looks like spanner setup is incomplete. Potentially due to permission issues.

**Comment by codeactivist** [comment]
Going to close this issue, please reopen if you are still having issues after following the documentation.
