### ISSUE TITLE
Getting some error logs in truestreet

### ISSUE THREAD

**Issue by anassolanki675** [google/truestreet#6]
2022/04/29 07:48:52 Failed to prepare session, error: spanner: code = "NotFound", desc = "Session not found: projects/dev-294310/instances/devprom/databases/promdb/sessions/wedbkjwbigwe73bkb38bsdb"
2022/05/02 08:29:48 rowsToTimeseries failed: spanner: code = "Canceled", desc = "context canceled"
2022/05/02 08:29:48 dataClient read error : spanner: code = "Canceled", desc = "context canceled"

I am getting this kind of errors in truestreet

**Comment by codeactivist** [comment]
Does restarting truestreet process/container help ? Can you post logs and command line you are using ?

**Comment by anassolanki675** [comment]
I tried restarting it and getting same logs. I tried running truestreet on ubuntu machine and also on docker container.

**Comment by codeactivist** [comment]
Is this ubuntu machine a google cloud VM ? Is docker container running on same machine/VM ? If these are remote then spanner can delete session after session being idle for long time, which could lead to this problem. However I think this error should have been retried.

Please provide more information about your setup to determine the next steps.

**Comment by anassolanki675** [comment]
Truestreet in deployed on DigitalOcean server as a docker container. It means, it is remote.

**Comment by codeactivist** [comment]
Since this machine is external to cloud, you will need to properly authenticate and authorize docker using...
`gcloud auth login`
`gcloud auth configure-docker`

**Comment by anassolanki675** [comment]
It is authenticated and also connected with spanner but sometimes it gives above error. Prometheus is working fine.
Just want to now if this session error occurs, will data be lost?

**Comment by codeactivist** [comment]
Session error is retried, however if problem persists for a long time, both truestreet or prometheus will drop buffered timeseries without sending to their remote storage. It is always a good idea to run two redundant (prometheus + truestreet + spanner schema) stacks to avoid data loss.
