### ISSUE TITLE
Getting permission denied error

### ISSUE THREAD

**Issue by anassolanki675** [google/truestreet#7]
2022/05/05 17:04:28 failed to set up Cloud Spanner clients : rpc error: code = PermissionDenied desc = Caller is missing IAM permission spanner.databases.list on resource projects/

**Comment by codeactivist** [comment]
Error appears to be pretty clear about missing permissions. User/Service account/VM running truestreet should have permission to create initial database schema and afterwards truestreet needs permissions to list, connect, insert and update data in the spanner DB.

You can use cloud IAM to grant these permissions to the truestreet.

**Comment by anassolanki675** [comment]
I have granted owner permission and it was working fine from last 10 days. it stopped working since yesterday.
